# Generated by Django 2.1.5 on 2019-07-19 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_type', models.CharField(max_length=5, verbose_name='选项类型')),
                ('choice_content', models.CharField(max_length=100, verbose_name='选项内容')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=20, verbose_name='题库名')),
                ('question_num', models.IntegerField(verbose_name='题号')),
                ('question_name', models.CharField(max_length=300, verbose_name='题目')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_test.QuestionBank'),
        ),
    ]
