# Generated by Django 2.1.2 on 2019-07-21 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBTIAnwserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anwser_type', models.CharField(choices=[('E', 'E'), ('I', 'I'), ('S', 'S'), ('N', 'N'), ('T', 'T'), ('F', 'F'), ('J', 'J'), ('P', 'P')], max_length=5, verbose_name='答案类型')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_test.Choice')),
            ],
        ),
    ]
