# Generated by Django 2.1.2 on 2019-07-28 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career_test', '0005_auto_20190726_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='HollandData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_num', models.IntegerField(verbose_name='号码')),
                ('part_title', models.CharField(max_length=30, verbose_name='标题')),
            ],
        ),
        migrations.CreateModel(
            name='HollandDataItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_num', models.IntegerField(verbose_name='号码')),
                ('part_type', models.CharField(max_length=2, verbose_name='类型')),
                ('content', models.CharField(max_length=100, verbose_name='内容')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_test.HollandData')),
            ],
        ),
        migrations.AlterField(
            model_name='mbtianwsertype',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_test.Choice'),
        ),
    ]
