# Generated by Django 2.1.2 on 2019-07-28 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career_test', '0006_auto_20190729_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbtianwsertype',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_test.Choice'),
        ),
    ]
