# Generated by Django 2.1.4 on 2019-07-29 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career_test', '0007_auto_20190729_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='HollandTypeResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(max_length=2, verbose_name='类型')),
                ('result_title', models.CharField(max_length=30, verbose_name='标题')),
                ('result_detail', models.CharField(max_length=300, verbose_name='内容')),
            ],
        ),
        migrations.AlterField(
            model_name='mbtianwsertype',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_test.Choice'),
        ),
    ]
