# Generated by Django 2.1.2 on 2019-08-11 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career_test', '0009_auto_20190807_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewHollandResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(max_length=3, verbose_name='类型名称')),
                ('result_content', models.CharField(max_length=300, verbose_name='内容')),
            ],
        ),
        migrations.AlterModelOptions(
            name='newholland',
            options={'ordering': ['title_num']},
        ),
        migrations.AlterModelOptions(
            name='newhollandtype',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='mbtianwsertype',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_test.Choice'),
        ),
    ]
