# Generated by Django 2.1.2 on 2019-08-11 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career_test', '0010_auto_20190811_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newhollandresult',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='mbtianwsertype',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_test.Choice'),
        ),
        migrations.AlterField(
            model_name='newhollandresult',
            name='result_type',
            field=models.TextField(verbose_name='类型名称'),
        ),
    ]
