# Generated by Django 2.1.5 on 2019-07-19 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='部门名称')),
                ('brief_introduction', models.CharField(blank=True, max_length=500, null=True, verbose_name='部门简介')),
                ('is_delete', models.BooleanField(verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名字')),
                ('phone_num', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码')),
                ('grade', models.CharField(max_length=4, verbose_name='年级')),
                ('school_department', models.CharField(max_length=10, verbose_name='系别')),
                ('major', models.CharField(max_length=20, verbose_name='专业')),
                ('personal_signature', models.CharField(blank=True, max_length=30, null=True, verbose_name='个性签名')),
                ('brief_introduction', models.CharField(blank=True, max_length=500, null=True, verbose_name='个人简介')),
                ('start_entry', models.DateField(blank=True, null=True, verbose_name='起始任职')),
                ('end_quit', models.DateField(blank=True, null=True, verbose_name='结束任职')),
                ('is_incumbent', models.BooleanField(verbose_name='是否在任')),
                ('is_first_generation', models.BooleanField(verbose_name='是否初代')),
                ('is_man', models.BooleanField(verbose_name='性别男')),
                ('is_delisting', models.BooleanField(verbose_name='是否除名')),
                ('work_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.Department')),
            ],
        ),
    ]
